//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Queue
    {
        public long Id { get; set; }
        public string Url { get; set; }
        public string Type { get; set; }
        public string Parameter { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
